//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.TransportData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class App
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string AppCode { get; set; }

        [DataMember]
        public string NameApp { get; set; }

        [DataMember]
        public byte Alias { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public string ModulesName { get; set; }

        [DataMember]
        public int CountModule { get; set; }

        [DataMember]
        public bool AppStatus { get; set; }
    }
}
