//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.TransportData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class CardTypeDTO
    {
        [DataMember]
        public int cardTypeID { get; set; }

        [DataMember]
        public String prefix { get; set; }

        [DataMember]
        public String cardTypeName { get; set; }

        [DataMember]
        public String cardLow { get; set; }

        [DataMember]
        public String cardHigh { get; set; }

        [DataMember]
        public int pinLength { get; set; }
    }
}
