//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using sWorldModel.TransportData;

    [DataContract]
    public class CardmagneticDTO
    {
        [DataMember]
        public long MagneticId { get; set; }

        [DataMember]
        public long OrgMasterId { get; set; }

        [DataMember]
        public long OrgPartnerId { get; set; }

        [DataMember]
        public string  MasterCode { get; set; }

        [DataMember]
        public string PartnerCode { get; set; }

        [DataMember]
        public string OrgName { get; set; }

        [DataMember]
        public string SubOrgName { get; set; }

        [DataMember]
        public string FullName { get; set; }

        [DataMember]
        public string Company { get; set; }

        [DataMember]
        public string PhoneNumber { get; set; }

        [DataMember]
        public string SerialCard { get; set; }

        [DataMember]
        public string TrackData { get; set; }

        [DataMember]
        public string PinCode { get; set; }

        [DataMember]
        public string ActiveCode { get; set; }

        [DataMember]
        public string TypeCrypto { get; set; }

        [DataMember]
        public string StartDate { get; set; }

        [DataMember]
        public string ExpireDate { get; set; }

        [DataMember]
        public int Status { get; set; }

        [DataMember]
        public int PrintStatus { get; set; }

        [DataMember]
        public int PhysicalStatus { get; set; }

        [DataMember]
        public string cardtypes { get; set; }

        [DataMember]
        public string Notes { get; set; }

       
    }
}
