//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.TransportData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class KeyDTO
    {
        [DataMember]
        public byte Id { get; set; }

        [DataMember]
        public byte Alias { get; set; }

        [DataMember]
        public string KeyValue { get; set; }

        [DataMember]
        public SectorKeyPairDTO Key { get; set; } //hex

    }
}
