
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.TransportData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class Member
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public long SubOrgId { get; set; }

        [DataMember]
        public long OrgId { get; set; }

        [DataMember]
        public string OrgCode { get; set; }

        [DataMember]
        public string Code { get; set; }

        [DataMember]
        public string Title { get; set; }

        [DataMember]
        public string FirstName { get; set; }

        [DataMember]
        public string LastName { get; set; }

        [DataMember]
        public string LowerFullName { get; set; }

        [DataMember]
        public string BirthDate { get; set; }

        [DataMember]
        public int Gender { get; set; }

        [DataMember]
        public string Degree { get; set; }

        [DataMember]
        public string Position { get; set; }

        [DataMember]
        public string PermanentAddress { get; set; }

        [DataMember]
        public string TemporaryAddress { get; set; }

        [DataMember]
        public string PhoneNo { get; set; }

        [DataMember]
        public string Email { get; set; }

        [DataMember]
        public string Nationality { get; set; }

        [DataMember]
        public string ImagePath { get; set; }

        [DataMember]
        public string CreatedDate { get; set; }

        [DataMember]
        public string ModifiedDate { get; set; }

        [DataMember]
        public string HashCode { get; set; }

        [DataMember]
        public bool Active { get; set; }

        [DataMember]
        public string Companyname { get; set; }

        [DataMember]
        public String IdentityCard { get; set; }

        [DataMember]
        public String IdentityCardIssueDate { get; set; }

        [DataMember]
        public String IdentityCardIssue { get; set; }

        [DataMember]
        public string ImgMember { get; set; }
        [DataMember]
        public String ContactName { get; set; }
        [DataMember]
        public String ContactPhone { get; set; }
        [DataMember]
        public String ContactEmail { get; set; }
        [DataMember]
        public String ContactAddress { get; set; }

        public string GetFullName()
        {
            string firstName = FirstName == null ? string.Empty : FirstName.Trim();
            string lastName = LastName == null ? string.Empty : LastName.Trim();
            return string.Format("{0} {1}", lastName, firstName);
        }
    }

}

