//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.TransportData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class PolicySworld
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public long GroupId { get; set; }

        [DataMember]
        public int ModuleId { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public int Modify { get; set; }

        [DataMember]
        public int Insert { get; set; }

        [DataMember]
        public int Delete { get; set; }

        [DataMember]
        public int View { get; set; }
    }
}
