//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.TransportData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class UserSworld
    {
        [DataMember]
        public long id { get; set; }

        [DataMember]
        public long GroupId{ get; set; }

        [DataMember]
        public long memberid{ get; set; }

        [DataMember]
        public long orgId{ get; set; }

        [DataMember]
        public String UserName{ get; set; }

        [DataMember]
        public String PasswordHash{ get; set; }

        [DataMember]
        public bool IsRoot{ get; set; }

        [DataMember]
        public int Status{ get; set; }

        [DataMember]
        public String FirstName{ get; set; }

        [DataMember]
        public String LastName{ get; set; }

        [DataMember]
        public String BirthDate{ get; set; }

        [DataMember]
        public String Email{ get; set; }

        [DataMember]
        public String PhoneNo{ get; set; }

        [DataMember]
        public String Gender{ get; set; }

        [DataMember]
        public String IdCardIssuedDate{ get; set; }

        [DataMember]
        public String IdCardIssuedPlace{ get; set; }

        [DataMember]
        public String IdCardNo{ get; set; }

        [DataMember]
        public String Nationality{ get; set; }

        [DataMember]
        public String PermanentAddress{ get; set; }

        [DataMember]
        public String TemporaryAddress{ get; set; }

        [DataMember]
        public String salt{ get; set; }

        [DataMember]
        public String code{ get; set; }

        [DataMember]
        public String ip{ get; set; }

        [DataMember]
        public String date_created{ get; set; }

        [DataMember]
        public String date_updated{ get; set; }

        [DataMember]
        public String local_code{ get; set; }


        public string GetFullName()
        {
            string firstName = FirstName == null ? string.Empty : FirstName;
            string lastName = LastName == null ? string.Empty : LastName;
            return string.Format("{0} {1}", lastName, firstName);
        }
    }
}
