//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class AMSCardmagneticAppDto
    {
        [DataMember]
        public long cardmagneticId { get; set; }

        [DataMember]
        public long AppId { get; set; }

        [DataMember]
        public string AppCode { get; set; }

        [DataMember]
        public long MagneticPersoId { get; set; }

        [DataMember]
        public string Rule { get; set; }

        [DataMember]
        public Nullable<sbyte> Status { get; set; }
    }
}
