//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class CMSAcquirerDto
    {
        [DataMember]
        public int AcquirerId { get; set; }

        [DataMember]
        public string AcquierMasterCode { get; set; }

        [DataMember]
        public string AccessCode { get; set; }

        [DataMember]
        public string Rule { get; set; }

        [DataMember]
        public string Desciption { get; set; }

        [DataMember]
        public string CreatedBy { get; set; }

        [DataMember]
        public string CreatedOn { get; set; }

        [DataMember]
        public string ModifiedBy { get; set; }

        [DataMember]
        public string ModifiedOn { get; set; }

        [DataMember]
        public string Status { get; set; }
    }
}
