//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class CMSCardchipDto
    {
        [DataMember]
        public long CardChipId { get; set; }

        [DataMember]
        public long OrgMasterId { get; set; }

        [DataMember]
        public long OrgPartnerId { get; set; }

        [DataMember]
        public long SecretKeyId { get; set; }

        [DataMember]
        public string OrgMasterCode { get; set; }

        [DataMember]
        public string OrgPartnerCode { get; set; }

        [DataMember]
        public string SerialNumberHex { get; set; }

        [DataMember]
        public int TypeCard { get; set; }

        [DataMember]
        public string TypeCrypto { get; set; }

        [DataMember]
        public string KeyPosition { get; set; }

        [DataMember]
        public System.DateTime CreatedOn { get; set; }

        [DataMember]
        public string CreatedBy { get; set; }

        [DataMember]
        public string ModifyBy { get; set; }

        [DataMember]
        public Nullable<System.DateTime> ModifyOn { get; set; }

        [DataMember]
        public int LogicalStatus { get; set; }

        [DataMember]
        public int PhysicalStatus { get; set; }

        [DataMember]
        public string swtgp_cms_cardchipcol { get; set; }
    }
}
