//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class CMSCardmagneticDto
    {
        [DataMember]
        public long MagneticId { get; set; }

        [DataMember]
        public long OrgMasterId { get; set; }

        [DataMember]
        public long OrgPartnerId { get; set; }

        [DataMember]
        public long SecretKeyId { get; set; }

        [DataMember]
        public string IssuerCode { get; set; }

        [DataMember]
        public string PartnerCode { get; set; }

        [DataMember]
        public string CardNumber { get; set; }

        [DataMember]
        public string Track1Data { get; set; }

        [DataMember]
        public string Track2Data { get; set; }

        [DataMember]
        public string Track3Data { get; set; }

        [DataMember]
        public string PinCode { get; set; }

        [DataMember]
        public string ActiveCode { get; set; }

        [DataMember]
        public string TypeCrypto { get; set; }

        [DataMember]
        public string StartDate { get; set; }

        [DataMember]
        public string ExpireDate { get; set; }

        [DataMember]
        public Nullable<int> LogicalStatus { get; set; }

        [DataMember]
        public Nullable<int> PhysicalStatus { get; set; }
    }
}
