//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ConfigDto
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public long SessionTimeToLive { get; set; }

        [DataMember]
        public long SessionClearingDelay { get; set; }

        [DataMember]
        public long PasswordHashLoop { get; set; }
    }
}
