//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class HSMDto
    {
        [DataMember]
        public long HsmId { get; set; }

        [DataMember]
        public string NameAlgorithm { get; set; }

        [DataMember]
        public string Formatvalue { get; set; }

        [DataMember]
        public string Values { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public Nullable<bool> Status { get; set; }
    }
}
