//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class IntegratingLogDto
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string ChangedTable { get; set; }

        [DataMember]
        public string Changes { get; set; }

        [DataMember]
        public bool Result { get; set; }

        [DataMember]
        public string Reason { get; set; }

        [DataMember]
        public string ChangedType { get; set; }

        [DataMember]
        public System.DateTime ChangedOn { get; set; }

        [DataMember]
        public string ChangedBy { get; set; }
    }
}
