//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class LoginHistoryDTO
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string UserName { get; set; }

        [DataMember]
        public System.DateTime LoginTime { get; set; }

        [DataMember]
        public Nullable<System.DateTime> LogoutTimt { get; set; }

        [DataMember]
        public bool Result { get; set; }

        [DataMember]
        public int FailedCode { get; set; }
    }
}
