//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class PSChipPersonalizationDto
    {
        [DataMember]
        public long ChipPersoId { get; set; }

        [DataMember]
        public long PsMemberId { get; set; }

        [DataMember]
        public long CardChipId { get; set; }

        [DataMember]
        public string SerialNumber { get; set; }

        [DataMember]
        public string Data { get; set; }

        [DataMember]
        public System.DateTime PersoDate { get; set; }

        [DataMember]
        public Nullable<System.DateTime> ExpirationDate { get; set; }

        [DataMember]
        public string Notes { get; set; }

        [DataMember]
        public string CreatedBy { get; set; }

        [DataMember]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [DataMember]
        public string ModifiedBy { get; set; }

        [DataMember]
        public Nullable<System.DateTime> ModifiedOn { get; set; }

        [DataMember]
        public string Temp1 { get; set; }

        [DataMember]
        public int Status { get; set; }
    }
}
