//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWorldModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class PSMagneticPersonalizationDto
    {
        [DataMember]
        public long MagneticId { get; set; }

        [DataMember]
        public long PsMemberId { get; set; }

        [DataMember]
        public long CardMagneticId { get; set; }

        [DataMember]
        public string SerialCard { get; set; }

        [DataMember]
        public string Track1Data { get; set; }

        [DataMember]
        public string Track2Data { get; set; }

        [DataMember]
        public string Track3Data { get; set; }

        [DataMember]
        public string PinCodeNew { get; set; }

        [DataMember]
        public string ActiveCodeNew { get; set; }

        [DataMember]
        public System.DateTime PersoDate { get; set; }

        [DataMember]
        public Nullable<System.DateTime> ExpirationDate { get; set; }

        [DataMember]
        public string Notes { get; set; }

        [DataMember]
        public int Status { get; set; }
    }
}
